# Continous Integration Script
# Clinica - ARAMIS
#

stages:
  - build
  - install
  - test
  - package 

    #variables:
    #  BIDS_TEST: "/localdrive10TB/data/gitlab-runner/BIDS_TEST"
    #  CAPS_TEST: "/localdrive10TB/data/gitlab-runner/CAPS_TEST"
    #  WD_TEST: "/localdrive10TB/data/gitlab-runner/WD_TEST"
    #  ENVIRONMENT_TEST: "/export/applications/clinica/Ubuntu14.04/dot_path"

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
    CLINICA_ENV_BRANCH: "clinica_env_$CI_COMMIT_REF_NAME"

cache:
  paths:
    - .cache/

before_script:
  - pwd
after_script:
  #  - conda env remove -y  --name clinica_env_upgrade_dep

build:mac:
  stage: build
  tags:
    - macOS
  script:
    # If the environment already exists or if it's changed
    # (by editing the environment.yml file), the environment
    # is recreated.
    - >
      if conda env list|grep -w "clinica_env_upgrade_dep"; then
        if git diff HEAD~ --name-only|grep environment.yml; then
          echo "REcreate environment clinica_env_upgrade_dep"
          conda env create --force --file environment.yml -n clinica_env_upgrade_dep
        fi;
      else
        echo "Create environment clinica_env_upgrade_dep"
        conda env create --force --file environment.yml -n clinica_env_upgrade_dep
      fi;

build:linux:
  stage: build
  tags:
    - linux
  script:
    # If the environment already exists or if it's changed
    # (by editing the environment.yml file), the environment
    # is recreated.
    - >
      if conda env list|grep -w "clinica_env_upgrade_dep"; then
        if git diff HEAD~ --name-only|grep environment.yml; then
          echo "REcreate environment clinica_env_upgrade_dep"
          conda env create --force --file environment.yml -n clinica_env_upgrade_dep
        fi;
      else
        echo "Create environment clinica_env_upgrade_dep"
        conda env create --force --file environment.yml -n clinica_env_upgrade_dep
      fi;

launch:mac:
  # Install python dependencies for  Clinica 
  stage: install 
  tags:
    - install
    - macOS
  script:
    - source activate clinica_env_upgrade_dep
    - pip install --ignore-installed .
    - eval "$(register-python-argcomplete clinica)"
    - clinica --help
    - source deactivate
  

launch:linux:
  # Install python dependencies for  Clinica 
  stage: install
  tags:
    - install
    - linux
  script:
    - source activate clinica_env_upgrade_dep
    - pip install --ignore-installed .
    - eval "$(register-python-argcomplete clinica)"
    - clinica --help
    - source deactivate

      
unittest:mac:
  stage: test
  tags:
    - macOS
  script:
    - source activate clinica_env_upgrade_dep
    - module load clinica.all
    - cd test
    - ln -s /Volumes/builds/Clinica/data_ci_mac ./data
    - pytest --verbose -k instantiate
    - module purge
    - source deactivate

  
unittest:linux:
  stage: test
  tags:
    - linux
  script:
    - source activate clinica_env_upgrade_dep
    - export PATH="/home/gitlab-runner/dcm2nii":${PATH}
    - module load clinica.all
    - module unload clinica/freesurfer/5.3.0
    - module load clinica/freesurfer/6.0.0
    - cd test
    - ln -s /localdrive10TB/data/data_ci_linux_branch-upgrade_dep ./data
    - taskset -c 0-21 pytest --verbose --timeout=0 -n 6 -k run
    - module purge
    - source deactivate

pkg:
  stage: package
  tags:
    - macOS
  script:
    - tar -cvzf --exclude='.gitignore' --exclude='.git' --exclude='.DS_Store' --exclude='.gitmodules' --exclude='.idea' --exclude='.vscode' --exclude='.gitlab-ci.yml' -f clinica-$CI_COMMIT_REF_NAME.tar.gz  ./*
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - clinica-$CI_COMMIT_REF_NAME.tar.gz
  only:
    - tags
