name: clinica_env_upgrade_dep
channels:
  - conda-forge
  - Aramislab
  - defaults
dependencies:
  - python==3.6
  - pip=18.0
  - pip :
      nibabel>=2.0.2
      nipype==1.1.2
      pybids==0.5.1
      dipy>=0.14.0
      argcomplete>=1.4.1
      pandas>=0.18.1
      nose>=1.3.7
      jinja2>=2.9
      xvfbwrapper>=0.2.8
      networkx<2.0.0
      plinkio>=0.9.6
      six>=1.9.0
      numpy>=1.8.2
      scipy>=0.13.3
      scikit-learn>=0.18.2
      scikit-image>=0.13.*
      sharedmem>=0.3.5
      xlrd>=0.9.0
      grabbit==0.1.1
      colorama>=0.3.9
      prov==1.5.0
      pytest>=3.4.0
      pydot==1.2.4
      pytest-xdist==1.22.5
      pytest-timeout==1.3.1

