# Project information
site_name: 'Clinica Documentation'
site_description: 'Clinica Documentation'
site_author: 'Clinica developers'
site_url: 'http://www.clinica.run'
#docs_dir: _docs # Useful if a Jekyll theme is used: https://github.com/CloudCannon/edition-jekyll-template
site_dir: www.clinica.run/www/doc

# Repository
repo_name: 'aramislab/clinica'
repo_url: 'https://github.com/aramis-lab/clinica'
#edit_uri: 'master/edit/doc'

# Copyright
copyright: 'Copyright &copy; 2016-2019 Clinica'

# Google Analytics
google_analytics:
  - 'UA-106080699-1'
  - 'auto'

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Options:
extra:
  logo: 'img/clinica_logo.svg'
  feature:
    tabs: true
  social:
    - type: 'github'
      link: 'https://github.com/aramis-lab/'
    - type: 'twitter'
      link: 'https://twitter.com/aramislabparis'
    - type: 'globe'
      link: 'http://www.aramislab.fr/'

#use_directory_urls: false # Use this when you work locally

# Extensions:
markdown_extensions:
  - admonition
  - codehilite:
     linenums: False
  - footnotes
  - toc:
      permalink: True
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: True
  - pymdownx.keys

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - css/clinica.css

# Pages:
nav:
  - Home: "index.md"
  - Installation:
    - "Installation": "Installation.md"
    - "Third-party": "Third-party.md"
    # - "Before your install": "BeforeYouInstall"
    # - "ICM cluster installation": "ICMClusterInstallation"
  # - Quick start:
  - Clinica environment:
    - "What is Clinica?": "WhatIsClinica.md"
    - "Interacting with Clinica": "InteractingWithClinica.md"
    - "BIDS": "BIDS.md"
    - CAPS:
      - "Introduction": "CAPS/Introduction.md"
      - "Overview": "CAPS/Overview.md"
      - "Specifications": "CAPS/Specifications.md"
    - "Atlases": "Atlases.md"
  - Pipelines:
    - Anatomical MRI:
      - "Volume processing": "Pipelines/T1_Volume.md"
      - "FreeSurfer processing": "Pipelines/T1_FreeSurfer.md"
    - DWI:
      - "Pre-processing": "Pipelines/DWI_Preprocessing.md"
      - "DTI": "Pipelines/DWI_DTI.md"
  #    - "Connectome": "Pipelines/DWI_Connectome"
    - fMRI:
      - "Pre-processing": "Pipelines/fMRI_Preprocessing.md"
    - PET:
      - "Volume processing": "Pipelines/PET_Volume.md"
      - "Surface processing": "Pipelines/PET_Surface.md"
    - Statistics:
      - "Surface-based mass-univariate analysis with SurfStat": "Pipelines/Stats_Surface.md"
    - Machine Learning:
      - "Prepare input data for spatially regularized SVM": "Pipelines/MachineLearning_PrepareSVM.md"
      - "Classification based on machine learning": "Pipelines/MachineLearning_Classification.md"
  - Dataset converters:
    - "ADNI to BIDS": "DatabasesToBIDS#adni-to-bids"
    - "AIBL to BIDS": "DatabasesToBIDS#aibl-to-bids"
    - "OASIS to BIDS": "DatabasesToBIDS#oasis-to-bids"
  - I/O tools:
    - "create-subjects-visits": "IO#create-subjects-visits-generate-the-list-all-subjects-and-visits-of-a-given-dataset"
    - "check-missing-modalities": "IO#check-missing-modalities-check-missing-modalities-for-each-subject"
    - "merge-tsv": "IO#merge-tsv-gather-bids-and-caps-data-into-a-single-tsv-file"
  - Presentations & demos:
    - "NOW 2019": "ClinicaConferences#neuro-openscience-workshop-2019"
    - "OHBM 2018": "ClinicaConferences#educational-course-on-pattern-recognition-for-clinical-neuroimaging-ohbm-2018"
  # - Collaborate:
    # - "Coding for Clinica": "CodingForClinica"
